title: GitReleaseGenerator
description: Generate clean release notes from your Git history.

theme: just-the-docs
# To use remote_theme instead, comment out the line above and uncomment below.
# remote_theme: just-the-docs/just-the-docs

url: "" # Set for production host
baseurl: "" # Keep empty when deploying at domain root

just_the_docs:
  aux_links:
    "View on GitHub": https://github.com/bjornefisk/gitreleasegen
  aux_links_new_tab: true
  color_scheme: light
  search_enabled: true

nav_external_links:
  - title: GitHub Repo
    url: https://github.com/bjornefisk/gitreleasegen

